pipeline {
    agents any
    stages {
        stage("Test") {
            steps {
                echo 'Hello from jenkins'
                pwd
            }
        }
        stage("Make the poll work") {
            steps {
                echo 'This should show up!'
            }
        }
    }
}
