pipeline {
    agent any
    stages {
        stage('Beta') {
            steps {
                echo 'hello'
                echo 'this is something that is pretty cool'
            }
        }
    }
}
