pipeline {
    agent any
    stages {
        stage('Testing Docker Capabilities') {
            steps {
                echo 'this is pretty cool!'
                echo 'look at this jenkins job!'
            }
        }
    }
}
